version: "3.9"

services:
  web:
    build: .
    image: cytemi5000/myapp:latest
    container_name: myapp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/myapp
    ports:
      - "9000:8000"
    env_file:
      - .env

